### ISSUE TITLE
jscpd signs one line before real copy/pasted block as part of duplication

### ISSUE THREAD

**Issue by evgygor** [kucherenko/jscpd#154]
Examples:
jscpd reports - 
```
     auto_login.brs: 140-151
     auto_login.brs: 235-246
```
Same thing jscpd vscode extension visualizes: 

![image](https://user-images.githubusercontent.com/10452376/43247877-b481b3a0-90be-11e8-98d5-593c292cad63.png)

Please see that lines 140 and 235 are different
Actually the detected block should be 141 - 151 and 236 - 246.

Thanks

**Comment by kucherenko** [comment]
Thank you for reporting.
The main problem of the issue is the start token of duplication is located on the previous line, it can be the new_line token or some punctuation. Any way I can skip the symbols but it can break reports for some languages, like python. I'm going to add to report start position of duplication.

**Comment by kucherenko** [comment]
Implemented in alpha version of jscpd
