### ISSUE TITLE
HTML report does not render code correctly

### ISSUE THREAD

**Issue by xqin** [kucherenko/jscpd#550]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1265888/199439071-8afa102f-72cf-4799-9e72-e4b72579b2ec.png)

![image](https://user-images.githubusercontent.com/1265888/199439180-aa7584b4-f18b-4500-b26b-1879c4196868.png)

**To Reproduce**
1. 1.js as same with 2.js
```
const axios = require('axios')

function test ({ code, message, _, response }) => { // 服务端响应为非 200 的场景, 都到 catch 这里
  console.log(`hello !@#LK><M>
\n
          <M`)
  console.log('hello !@#LK><M> \n <M')

  return axios(option).then((response) => {
    const { code, success, message, data } = response.data || {}
    const ok = (!!success && code === '200')
    return ok
  })
}
```

3. run command `npx jscpd -r html ./*.js`

**Expected behavior**
render code correctly

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  linux 
 - OS Version alpine 3.16.2
 - NodeJS Version v16.17.1
 - jscpd version 3.5.1

**Additional context**

render `clone.fragment` as html, may fix this bug.

ref:  https://vuejs.org/guide/essentials/template-syntax.html#raw-html

![image](https://user-images.githubusercontent.com/1265888/199439831-ee64df8b-befa-44fe-a7fa-f3e805caf694.png)

**Comment by soullivaneuh** [comment]
I confirm the problem. Plus, using `npx jscpd@3.4.5` does not fix it, surely because the `@jscpd/html-reporter` package is installed to the latest version. I did not find any way to workaround this.

Here is the change I suspect it introduces the bug: https://github.com/kucherenko/jscpd/commit/5dc30bf30820594fb5488e42c7aa33a6d0ea326d

cc @kucherenko @zhaoyi
